agent_name: "PG"

model:
  actor_net: "fc_2layers_128units"
  actor_init_output_scale: 0.01
  actor_std_type: "FIXED"
  action_std: 0.2
  
  critic_net: "fc_2layers_128units"


discount: 0.99
steps_per_iter: 4096
iters_per_output: 50
test_episodes: 32
critic_update_epoch: 5

# optimizer parameters
actor_learning_rate: 8e-3 ## 2e-3
critic_learning_rate: 8e-3 ## 2e-3

batch_size: 512
norm_adv_clip: 4.0
action_bound_weight: 10.0